### ISSUE TITLE
Автоматическое переподключение

### ISSUE THREAD

**Issue by Paranoiiik** [Reg1oxeN/ClientMod-Api#2]
Может, можно добавить в API возможность заставлять игроков переподключаться к серверу через определённое количество секунд, если сервер аварийно завершил свою работу?

**Comment by Reg1oxeN** [comment]
а как по твоему клиент должен определить что сервер аварийно завершил свою работу?

**Comment by Paranoiiik** [comment]
Увидел такое тут - https://hlmod.ru/resources/linux-cassandra.1766/
Подумал, что, поскольку есть возможность взаимодействовать с клиентом, такое будет легче провернуть, если вообще возможно.
Не спорю.. идея может быть очень даже глупой, я ведь не разбираюсь :с
